client/src/components/PostsContainer.tsx

**Just the inicialization** of the component, i will countinue with this **tomorrow**.

feat(Created PostsContainer component): client

---

api/controllers/userController.ts
api/prisma/migrations/20220119155542_init/migration.sql
api/prisma/schema.prisma
api/routes/company.ts
api/routes/post.ts
api/routes/role.ts
api/routes/user.ts

Creé las relaciones entre los modelos User y Post

Database relations

---

client/src/redux/actions/actionTypes.ts
client/src/redux/actions/index.ts
client/src/redux/reducers/postsReducer.ts
client/src/redux/reducers/rootReducer.ts

- I've initialized the reducer 'postsReducer' with a simple initial state.
- Created the index file for actions and set some basic actions.
- All works perfectly.

feature(ReduxContext): improve the context of the state management.

---

api/controllers/userController.ts
api/routes/user.ts

* Ruta para user Profile funcionando ok.
* (recuerden que habíamos quedado en utilizar email para que puedan tener acceso desde front, más adelante será con el id seguramente)

✨ route user/:id created

---

api/index.ts
api/package.json
api/passport.ts
api/routes/auth.ts
client/src/App.tsx
client/src/components/Login.tsx
client/src/components/Logout.tsx
client/src/components/NavBar.tsx
client/src/pages/Home.tsx
client/src/pages/UserProfile.tsx
client/src/pages/WelcomePage.tsx

feat(login-logout): ✨

---

client/src/App.tsx
client/src/components/PostDetail.tsx
client/src/pages/PostDetail.tsx

Creación del componente post detail
Falta crear redux para adaptar el componente y que quede el final

✨ front post detail

---

api/README.md
api/controllers/companyController.ts
api/controllers/postsController.ts
api/controllers/userController.ts
api/routes/company.ts
api/routes/index.ts
api/routes/posts.ts
api/routes/role.ts
api/routes/user.ts

tweaked router and added a few new routes
tested every single route all working except for createReviews, already informed the team and we'll get working on that

feat(router): ✨ tweaked router

---

api/README.md

Added a list of all the available routes! 
Check /api/README.md

docs(README): 📚 added a routes list on README.md

---

api/controllers/postsController.ts

fix(postController): 🐛 removed extra curly brace

---

api/controllers/userValidation.ts

on file /api/controllers/userValidation.ts I added a :string type declaration on the function params

fix(userValidation): 🐛 added :string to fn params

---

client/src/components/FavouritesButton.tsx
client/src/components/Post.tsx
client/src/services/checkExistance.ts

- checkExistance class added into services folder

FavouritesButton component added

---

client/src/components/CompanyProfile.tsx

- Chequear la reutilización del componente Profile, compartido con UserProfile.tsx
- Definir el funcionamiento de dichos componentes.

feat(Create component): create CompanyProfile.tsx ✨

---

client/src/pages/AboutUs/AboutUs.tsx
client/src/pages/AboutUs/styles.ts

Dumb component about us.
Replace information.

feat(AboutUs): page created ✨

---

client/src/components/Favorites.tsx

Tengo la idea de que a este componente lo podríamos reultilizar para las notifications... 
Luego podemos ver de modificarlos.

feat(FavoritesModal):component created ✨

---

client/src/components/PostsContainer.tsx
client/src/components/PostsNavBar.tsx

- En este Commit agregué la logica de paginado al componente PostsContainer.
- Cambié de lugar el paginado. Ahora esta dentro de Posts Container para no tener que andar pasando muchos datos por props. REVISENLO y si tienen dudas me escriben.

feat(Paginated Posts): ✨ paginated logic added

---

api/routes/company.ts

Se soluciono el problema de la ruta update/:companyId

route update ok  📦

---

api/controllers/notificationController.ts
api/routes/index.ts
api/routes/notification.ts

Cree rutas de notification y las testee

feat(notification):✨ created routes and tested them

---

api/controllers/newsController.ts
api/routes/index.ts
api/routes/news.ts

created routes and tested them

feat(news): ✨ created routes and tested them

---

client/src/components/FollowCompanyButton.tsx

- Componente para seguir empresas y recruiters
- Va en CompanyProfile.
Intenté hacerlo parte del componente Favorites para reutilizarlo pero hay mucho lío..
Mejor intentemos llegar con el proyecto y luego optimizamos :+1:

feat(FollowCompany): ✨ component created

---

api/controllers/notificationTypeController.ts
api/routes/index.ts
api/routes/notificationTypes.ts

created routrs and tested them

feat (notification types):✨ created routes and tested them

---

api/controllers/applicantController.ts
api/controllers/categoryController.ts
api/controllers/companyController.ts
api/controllers/educationController.ts
api/controllers/experienceController.ts
api/controllers/languagesController.ts
api/controllers/newsController.ts
api/controllers/notificationController.ts
api/controllers/notificationTypeController.ts
api/controllers/postsController.ts
api/controllers/tagsController.ts
api/controllers/userController.ts
api/controllers/userValidation.ts
api/prisma/lista.md

refactorice el codigo para que todo tenga el mismo estilo
agregue algunos feedbacks de campos faltantes para el front

refactor(controllers): 📦 unified code format

---

api/controllers/userController.ts

mejore el /user/create para que ya devuelva le relacion con applicant o user creado dependiendo de lo que pasaron en campo 'role'

feat(userController): ✨ improved user creation

---

api/controllers/applicantController.ts
api/controllers/postsController.ts
api/routes/applicant.ts

feat(apply applicant):✨ modified also post by id

feat(apply applicant):✨ modified also post by id

---

api/Tabla Rutas.md
api/controllers/userController.ts

actualice la rute /user/:email para que envie notifications tambien

feat(user-router): ✨ modified as per front req

---

api/controllers/applicantController.ts
api/routes/applicant.ts

* Cree las rutas de relaciones:
applicant/favourite
applicant/follow
(Con estas dos, ya estarían todas las rutas de relaciones hechas)

Relation routes ready ✨

---

api/controllers/notificationController.ts
api/prisma/migrations/20220127183531_init/migration.sql
api/prisma/migrations/20220127190805_init/migration.sql
api/prisma/schema.prisma
api/prisma/seed.ts

updated the seeder so that the generated database is more complete for testing

feat(seeder): ✨ seeder got chunkier

---

client/src/App.tsx
client/src/components/Menus/PrivateMenu.tsx
client/src/components/Menus/PublicMenu.tsx
client/src/pages/Q&A/QandA.tsx
client/src/pages/Q&A/styles.ts

Dentro de los primeros cuadros estan las preguntas, haciendo click hace un scroll hacia abajo hasta donde está la respuesta.
Sume al Navbar la opcion de preguntas frecuentes.

feature(QandA): ✨ Nuevo componente con Ruta

---

api/controllers/applicantController.ts
api/prisma/schema.prisma

ruta apply ahora devuelve arreglo de postulaciones!

feat(applicant/apply): ✨ tweaked as per front req

---

client/src/components/Menus/PrivateMenu.tsx
client/src/components/Menus/PublicMenu.tsx
client/src/components/Notifications.tsx

Retoqué un poquito de Css de varios componentes

feature(notifications): ✨

---

api/controllers/applicantController.ts
api/prisma/migrations/20220127230214_init/migration.sql
api/prisma/migrations/20220128040511_init/migration.sql
api/prisma/migrations/20220128040613_init/migration.sql
api/prisma/schema.prisma

ruta /applicant/apply ahora devuelve un arreglo con los posts y sus status correspondientes

feat(/applicant/apply):✨formatted as per front req

---

.gitignore
api/package-lock.json
api/package.json

deploying server, making minor changes

feat(commands and ignore): ✨ deployment

---

api/controllers/applicantController.ts
api/prisma/schema.prisma

saque notificationTypes de la db y puli un poco el return de applicantController

feat(tweaked routes):✨dropped notificationTypes

---

api/prisma/seed.ts

seed.ts was crashing the server because of missing model, all good now

fix(seed.ts): 🐛 seed.ts was crashing server

---

api/controllers/applicantController.ts
api/controllers/userController.ts
api/prisma/schema.prisma
api/routes/applicant.ts

formatted the package returned by /user/:email as per frontend request

feat(user/email): ✨formatted returned package

---

client/src/components/Favorites.tsx

-Ahora si podemos acceder desde el modal hacia los detalles del trabajo!

feat(Favourites): ✨ Linked!!

---

api/prisma/schema.prisma
api/prisma/seed.ts

added fields "aboutValues" and "about" to Company model, and modified companyValues one, now called values and is an array of string

feat(schema.prisma): ✨added fields on company

---

api/controllers/applicantController.ts
api/controllers/companyController.ts
api/controllers/notificationController.ts
api/controllers/postsController.ts
api/controllers/userController.ts
api/prisma/schema.prisma
api/prisma/seed.ts
api/routes/company.ts
api/routes/index.ts

mejoradas y chequeadas rutas applicant/apply y company/application

feat(userRoute):✨tweaked route

---

api/Tabla Rutas.md
api/controllers/postsController.ts
api/routes/posts.ts

created /posts/update/:postId route
receives object with 'endDate' prop for updating
cannot update anything else for the time being

feat(posts-router):✨created update route

---

api/Tabla Rutas.md
api/controllers/postsController.ts

modificado el objeto retornado para que incluya los applicants del post

feat(postController):✨added applicants to returned object

---

api/Tutorial DB.md
api/controllers/companyController.ts
api/controllers/postsController.ts
api/prisma/schema.prisma
api/prisma/seed.ts
api/routes/company.ts

added score filter
modified returned object on /posts/index and /posts/filter so that they include the companyLogo prop

feat(routes):✨/posts/filter added score filter

---

api/controllers/postsController.ts
api/prisma/seed.ts

now the inputNames field on the /filter object sent by frontend is an array, filter returns any post where the title includes any of the strings in the array

feat(postsController):✨modified inputNames field

---

api/controllers/postsController.ts

added favorites field to returned object

feat(postsController): :sparkles: added favorites to returned object

---

api/controllers/applicantController.ts
api/controllers/paymentController.ts
api/index.ts
api/package-lock.json
api/package.json
api/routes/index.ts
api/routes/payment.ts

First implementation of Mercado Pago backend. 
We need to test the frontend and backend together

feat(mercado pago): ✨ First backend implementation of Mercado Pago

---

api/controllers/applicantController.ts

added toggle functionality to route so we can add and remove tags using the same route

feat(applicant/tags): :sparkles: added toggle functionality

---

client/src/components/EditCompanyProfile/AboutCompany.tsx
client/src/components/EditCompanyProfile/EditCompanyProfile.tsx
client/src/components/EditCompanyProfile/Mission.tsx
client/src/components/EditCompanyProfile/Values.tsx
client/src/components/EditCompanyProfile/Vission.tsx
client/src/redux/actions/actionCreators.ts
client/src/redux/reducers/companyReducer.ts

- All sections are now connected with backend and saving
data correctly.

feat(EditCompanyProfile): Connected with backend ✨

---

client/src/components/ApplicantsByPost.tsx
client/src/components/CompanyPostDetail.tsx
client/src/components/DataTable.tsx
client/src/components/Td.tsx
client/src/redux/actions/companyActionCreators.ts
client/src/redux/reducers/postsReducer.ts

Favorites Applicants FUNCIONANDOOOO~~~
Company Side <3

fix(FavoritesApplicants): Funciona Ferruccio!!!!!

---

client/src/components/DataTable.tsx
client/src/components/Td.tsx

Funcionando las keys y no renderizan mas Warnings!!!!
FUNCIONA FERRUCCIO!!!!!

fix(DataTable): debugg of keys on maps

---

client/src/components/ApplicantsByPost.tsx
client/src/components/CompanyPostDetail.tsx
client/src/components/DataTable.tsx

Filtros para la tabla de usuarios funcionando!

feat(Applicants-Filters): It works, Ferruccio!!! 

---

api/Tabla Rutas.md
api/controllers/userController.ts
api/prisma/schema.prisma
api/prisma/seed.ts
api/routes/user.ts

added route to reset user's password

feat(user/login/reset/:email): :sparkles:  added password reset

---

api/controllers/postsController.ts

added company property to returned object

feat(posts/:postId): :sparkles: added company property

---

api/controllers/userController.ts
api/routes/user.ts

Nueva ruta para convertir user en admin

new route user/admin ✨

---

api/package.json

added optional dependency for fsevents to package.json

fix: :bug: added optional dependency
